### ISSUE TITLE
Error in load-postgresql.py ?

### ISSUE THREAD

**Issue by psychemedia** [okfn/dptools#1]
In `load-postgresql.py`, should line 49 be:

```
['\n  "%s" %s' % (field['name'], mappings[field['type']])
                for field in fields]
```

rather than `field['id']`?

Also, documentation re: making the script executable:
- Line 1 - add eg `#!/usr/bin/env python`
- on downloading the file, make it executable: e.g. on Mac, from commandline in the same directory as the downloaded file,  `chmod ugo+x load-postgresql.py`
- testing by running from the commandline: `./load-postgresql.py http://data.okfn.org/data/core/bond-yields-uk-10y/datapackage.json`

By the by, if `http://data.okfn.org/data/core/PACKAGE_NAME/` conventionally has the data package at `http://data.okfn.org/data/core/PACKAGE_NAME/datapackage.json` should the file loader be able to accept eg `http://data.okfn.org/data/core/PACKAGE_NAME` and then guess the location of the JSON file, or given eg `http://data.okfn.org/data/core/PACKAGE_NAME/foo.csv` guess at stripping `foo.csv` and then trying with `datapackage.json` using the same path?

**Comment by rufuspollock** [comment]
All good suggestions. Re the patch could you do a pull request?

**Comment by psychemedia** [comment]
I think there are actually a few more issues with the original script... eg in the example above the date field in the datapackage doesn't load properly into postgres, so there maybe needs tightening up of the whole ingest thing. I guess generating a datapackage with a set of tests for each data type that can be defined in a table would be the, erm, thorough thing to do...?

My setup also had issues with the end of line characters when I just copy and pasted the sql that was generated, so think that maybe it makes sense to generate a sql file and than test data ingest using that.

I'm not really familiar with how datapackage specification has evolved in the time since the the script was written, so perhaps there are other issues too, or other elements that the script could draw on when generating the SQL?

**Comment by rufuspollock** [comment]
Good point. I also think we should probably split out scripts to their separate repos (or even just gists) and deprecate this repo (e.g. generate.py is out of date).

@psychemedia would you be up for taking on the postgresql script (with support to get it up to date)?

**Comment by pudo** [comment]
No way I can sell you gentlemen on a nice bit of SQLAlchemy core (not the ORM part)? It makes this stuff so much easier, you'd only need one script for both DB types and it'll iron over a lot of DBAPI weirdness, too.

**Comment by rufuspollock** [comment]
@pudo the precise point here is basically _no_ dependencies.

However, it would be _awesome_ to have Tabular Data Package support in e.g. https://github.com/pudo/dataset

**Comment by pudo** [comment]
Hm, dataset doesn't do data loading (and I get a lot of flack for the fact that it does data export, might move that out). Perhaps this would be a more attractive place to integrate? 

http://csvkit.readthedocs.org/en/latest/scripts/csvsql.html

**Comment by femtotrader** [comment]
This may help https://github.com/blaze/odo

**Comment by rufuspollock** [comment]
@femtotrader super-useful thank-you! And i note we're actually working on data package to sql right now in https://github.com/okfn/jts-sql

**Comment by femtotrader** [comment]
I'm here because of https://github.com/pydata/pandas-datareader/issues/80
feel free to help

**Comment by femtotrader** [comment]
https://github.com/okfn/jts-sql looks like https://dataset.readthedocs.org/
what are differences ?

**Comment by rufuspollock** [comment]
@femtotrader you really want to look at https://github.com/okfn/jsontableschema-py I think. JSON Table Schema is the core table descriptor spec at the heart of Tabular Data Package.

**Comment by ppKrauss** [comment]
Hi,  there are a README or tutorial for this script? 
how to do something like `python load-postgresql.py https://raw.githubusercontent.com/datasets/country-codes/master/datapackage.json` ?

-----
Error:
``` 
Traceback (most recent call last):
  File "load-postgresql.py", line 66, in <module>
    load(args.datapackage)
  File "load-postgresql.py", line 35, in load
    process_resource(finfo)
  File "load-postgresql.py", line 48, in process_resource
    for field in fields]
KeyError: 'id'
```

**Comment by rufuspollock** [comment]
FIXED.

@ppKrauss i'd just use the https://github.com/frictionlessdata/jsontableschema-sql-py - this has superseded this code here.
