### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by ppKrauss** [okfn/dptools#3]
No commits since 2013.

... need to add *status* "abandoned" at  [roadmap spreadsheet,  item 3.3](https://docs.google.com/spreadsheets/d/1lekupQNTsQ63yvvjhEfM3OFHf1jJzviu8WjcL5dcczM/).

**Comment by rufuspollock** [comment]
@ppKrauss i'd more say this is superseded. Almost everything here now has better versions in the new FD tooling.

Agree though that this should be clearly marked as deprecated.
